In [1]:
import pandas as pd
import numpy as np

In [2]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 067B-E231

 Directory of C:\Users\haluk\Documents\AI_\Become a Pro\Grant_prediction

10/28/2023  03:26 PM    <DIR>          .
10/26/2023  08:24 PM    <DIR>          ..
10/28/2023  02:58 PM    <DIR>          .ipynb_checkpoints
10/26/2023  08:24 PM            35,675 unimelb_example.csv
10/26/2023  08:24 PM           919,446 unimelb_test.csv
10/26/2023  08:24 PM         3,577,489 unimelb_training.csv
10/28/2023  02:58 PM            42,344 Untitled.ipynb
10/28/2023  01:44 PM            46,722 Untitled-Copy1.ipynb
10/28/2023  02:52 PM            49,997 Untitled-Copy2.ipynb
10/28/2023  03:26 PM            48,715 Untitled-Copy3.ipynb
               7 File(s)      4,720,388 bytes
               3 Dir(s)  663,463,112,704 bytes free


In [3]:
#pd.set_option('display.max_columns', None)
#pd.set_option('display.max_rows', None)

In [4]:
df = pd.read_csv("unimelb_training.csv")

C:\Users\haluk\AppData\Local\Temp\ipykernel_18792\1540268421.py:1: DtypeWarning: Columns (90,105,119,120,123,124,132,134,135,138,139,147,149,150,153,154,162,164,165,168,169,177,179,183,184,192,194,198,199,207,209,213,214,224,237,239,244) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("unimelb_training.csv")


In [5]:
df

Grant.Application.ID  Grant.Status Sponsor.Code Grant.Category.Code  \
0                        1             1          NaN                 NaN   
1                        2             1           2B                 10A   
2                        3             1          29A                 10B   
3                        4             1          40D                 10B   
4                        5             0          59C                 10A   
...                    ...           ...          ...                 ...   
8703                  8704             1          21A                 50A   
8704                  8705             1          21A                 50A   
8705                  8706             0         137A                 30B   
8706                  8707             1          21A                 50A   
8707                  8708             1          21A                 50A   

     Contract.Value.Band...see.note.A Start.date  RFCD.Code.1  \
0                                  A     8/11/05     280199.0   
1                                  B    11/11/05     280103.0   
2                                  A    14/11/05     321004.0   
3                                  C    15/11/05     270602.0   
4                                  A    16/11/05     260500.0   
...                               ...        ...          ...   
8703                               A    23/12/08     321028.0   
8704                               A    23/12/08     340299.0   
8705                              NaN   24/12/08          NaN   
8706                               A    24/12/08     280210.0   
8707                               A    24/12/08     321012.0   

      RFCD.Percentage.1  RFCD.Code.2  RFCD.Percentage.2  ...  Faculty.No..15  \
0                 100.0          0.0                0.0  ...             NaN   
1                  30.0     280106.0               30.0  ...             NaN   
2                  60.0     321216.0               40.0  ...             NaN   
3                  50.0     320602.0               50.0  ...             NaN   
4                  34.0     280000.0               33.0  ...             NaN   
...                 ...          ...                ...  ...             ...   
8703              100.0          0.0                0.0  ...             NaN   
8704               50.0     390114.0               50.0  ...             NaN   
8705                NaN          NaN                NaN  ...             NaN   
8706               40.0     239901.0               40.0  ...             NaN   
8707               70.0     321005.0               30.0  ...             NaN   

      With.PHD.15  No..of.Years.in.Uni.at.Time.of.Grant.15  \
0             NaN                                      NaN   
1             NaN                                      NaN   
2             NaN                                      NaN   
3             NaN                                      NaN   
4             NaN                                      NaN   
...           ...                                      ...   
8703          NaN                                      NaN   
8704          NaN                                      NaN   
8705          NaN                                      NaN   
8706          NaN                                      NaN   
8707          NaN                                      NaN   

      Number.of.Successful.Grant.15  Number.of.Unsuccessful.Grant.15  A..15  \
0                               NaN                              NaN    NaN   
1                               NaN                              NaN    NaN   
2                               NaN                              NaN    NaN   
3                               NaN                              NaN    NaN   
4                               NaN                              NaN    NaN   
...                             ...                              ...    ...   
8703                            NaN      

# DATA CLEANING

In [6]:
for col in df.columns:
    print(col)

Grant.Application.ID
Grant.Status
Sponsor.Code
Grant.Category.Code
Contract.Value.Band...see.note.A
Start.date
RFCD.Code.1
RFCD.Percentage.1
RFCD.Code.2
RFCD.Percentage.2
RFCD.Code.3
RFCD.Percentage.3
RFCD.Code.4
RFCD.Percentage.4
RFCD.Code.5
RFCD.Percentage.5
SEO.Code.1
SEO.Percentage.1
SEO.Code.2
SEO.Percentage.2
SEO.Code.3
SEO.Percentage.3
SEO.Code.4
SEO.Percentage.4
SEO.Code.5
SEO.Percentage.5
Person.ID.1
Role.1
Year.of.Birth.1
Country.of.Birth.1
Home.Language.1
Dept.No..1
Faculty.No..1
With.PHD.1
No..of.Years.in.Uni.at.Time.of.Grant.1
Number.of.Successful.Grant.1
Number.of.Unsuccessful.Grant.1
A..1
A.1
B.1
C.1
Person.ID.2
Role.2
Year.of.Birth.2
Country.of.Birth.2
Home.Language.2
Dept.No..2
Faculty.No..2
With.PHD.2
No..of.Years.in.Uni.at.Time.of.Grant.2
Number.of.Successful.Grant.2
Number.of.Unsuccessful.Grant.2
A..2
A.2
B.2
C.2
Person.ID.3
Role.3
Year.of.Birth.3
Country.of.Birth.3
Home.Language.3
Dept.No..3
Faculty.No..3
With.PHD.3
No..of.Years.in.Uni.at.Time.of.Grant.3
Number.of.

In [7]:
matching_columns = [col for col in df.columns if "Person.ID" in col]
print(matching_columns)

['Person.ID.1', 'Person.ID.2', 'Person.ID.3', 'Person.ID.4', 'Person.ID.5', 'Person.ID.6', 'Person.ID.7', 'Person.ID.8', 'Person.ID.9', 'Person.ID.10', 'Person.ID.11', 'Person.ID.12', 'Person.ID.13', 'Person.ID.14', 'Person.ID.15']


In [8]:
df.drop(matching_columns, axis=1, inplace = True)

In [9]:
matching_columns = [col for col in df.columns if "date" in col]
print(matching_columns)

['Start.date']


In [10]:
df.drop(matching_columns, axis=1, inplace = True)

In [11]:
matching_columns = [col for col in df.columns if "Country.of.Birth" in col]
print(matching_columns)

['Country.of.Birth.1', 'Country.of.Birth.2', 'Country.of.Birth.3', 'Country.of.Birth.4', 'Country.of.Birth.5', 'Country.of.Birth.6', 'Country.of.Birth.7', 'Country.of.Birth.8', 'Country.of.Birth.9', 'Country.of.Birth.10', 'Country.of.Birth.11', 'Country.of.Birth.12', 'Country.of.Birth.13', 'Country.of.Birth.14', 'Country.of.Birth.15']


In [12]:
df.drop(matching_columns, axis=1, inplace = True)

In [13]:
df.drop('Grant.Application.ID', axis=1, inplace = True)

In [14]:
matching_columns = [col for col in df.columns if "Home.Language" in col]
print(matching_columns)
df.drop(matching_columns, axis=1, inplace = True)
    

['Home.Language.1', 'Home.Language.2', 'Home.Language.3', 'Home.Language.4', 'Home.Language.5', 'Home.Language.6', 'Home.Language.7', 'Home.Language.8', 'Home.Language.9', 'Home.Language.10', 'Home.Language.11', 'Home.Language.12', 'Home.Language.13', 'Home.Language.14', 'Home.Language.15']


In [15]:
# Set the threshold for non-null values (90% threshold)
threshold = 0.8 * len(df)
# Drop columns with less than the threshold non-null values
df_cleaned = df.dropna(axis=1, thresh=threshold)

#df_cleaned= df.dropna(axis = 1, how = 'all', inplace = False)

In [16]:
df['Sponsor.Code'].fillna(0, inplace=True)

In [17]:
df['Sponsor.Code'].unique()

array([0, '2B', '29A', '40D', '59C', '4D', '28D', '136D', '100D', '1A',
       '21A', '24D', '148D', '12D', '62B', '138B', '60D', '143C', '90B',
       '18B', '89A', '34B', '47C', '36D', '32D', '172D', '184D', '5A',
       '63C', '74B', '6B', '170B', '166B', '101A', '33A', '164D', '75C',
       '161A', '157A', '9A', '126B', '149A', '53A', '94B', '97A', '160D',
       '51C', '167C', '135C', '65A', '42B', '87C', '169A', '95C', '103C',
       '147C', '133A', '150B', '155C', '174B', '83C', '175C', '139C',
       '202B', '13A', '168D', '113A', '134B', '20D', '141A', '80D', '91C',
       '187C', '26B', '162B', '93A', '84D', '158B', '55C', '77A', '429A',
       '140D', '23C', '142B', '112D', '111C', '154B', '185A', '151C',
       '3C', '428D', '137A', '37A', '146B', '176D', '145A', '85A', '14B',
       '69A', '41A', '427C', '49A', '7C', '44D', '163C', '144D', '177A',
       '39C', '153A', '173A', '159C', '178B', '156D', '186B', '152D',
       '171C', '201A', '182B', '183C', '52D', '132D', '21

In [18]:
df['Year.of.Birth.1'].unique()
df['Year.of.Birth.1'].fillna(df['Year.of.Birth.1'].mean(), inplace = True)
df['Year.of.Birth.1'] = 2010- df['Year.of.Birth.1'] -30

In [19]:
df['No..of.Years.in.Uni.at.Time.of.Grant.1'].value_counts(normalize= True)
df['No..of.Years.in.Uni.at.Time.of.Grant.1'].fillna('>=0 to 5', inplace = True)

In [20]:
df['No..of.Years.in.Uni.at.Time.of.Grant.1'].value_counts(normalize= True)

No..of.Years.in.Uni.at.Time.of.Grant.1
>=0 to 5        0.495062
>5 to 10        0.184084
Less than 0     0.118282
>10 to 15       0.105305
more than 15    0.097267
Name: proportion, dtype: float64

In [21]:
df['Number.of.Successful.Grant.1'].value_counts(normalize = True)
df['Number.of.Successful.Grant.1'].fillna(0, inplace=True)

In [22]:
df['Number.of.Unsuccessful.Grant.1'].value_counts(normalize = True)
df['Number.of.Unsuccessful.Grant.1'].fillna(0, inplace=True)

In [23]:
df['Grant.Category.Code'].value_counts(normalize = True)
df['Grant.Category.Code'].fillna('10A', inplace=True)


In [24]:
df_cleaned.isnull().sum()


Grant.Status                                 0
Sponsor.Code                               912
Grant.Category.Code                        912
RFCD.Code.1                                634
RFCD.Percentage.1                          634
RFCD.Code.2                                634
RFCD.Percentage.2                          634
RFCD.Code.3                                634
RFCD.Percentage.3                          634
RFCD.Code.4                                634
RFCD.Percentage.4                          634
RFCD.Code.5                                634
RFCD.Percentage.5                          634
SEO.Code.1                                 664
SEO.Percentage.1                           664
SEO.Code.2                                 664
SEO.Percentage.2                           664
SEO.Code.3                                 664
SEO.Percentage.3                           664
SEO.Code.4                                 664
SEO.Percentage.4                           664
SEO.Code.5   

In [25]:
df_= df_cleaned.dropna()

In [26]:
df_.isnull().sum()

Grant.Status                              0
Sponsor.Code                              0
Grant.Category.Code                       0
RFCD.Code.1                               0
RFCD.Percentage.1                         0
RFCD.Code.2                               0
RFCD.Percentage.2                         0
RFCD.Code.3                               0
RFCD.Percentage.3                         0
RFCD.Code.4                               0
RFCD.Percentage.4                         0
RFCD.Code.5                               0
RFCD.Percentage.5                         0
SEO.Code.1                                0
SEO.Percentage.1                          0
SEO.Code.2                                0
SEO.Percentage.2                          0
SEO.Code.3                                0
SEO.Percentage.3                          0
SEO.Code.4                                0
SEO.Percentage.4                          0
SEO.Code.5                                0
SEO.Percentage.5                

# MODEL 

In [27]:
#df_ = df_cleaned;
y = df_ ['Grant.Status']
x = df_.drop('Grant.Status', axis = 1, inplace = False)
#x = x.drop(['Start.date','Country.of.Birth.1'], axis = 1, inplace = False)
#x = x.drop(['Grant.Application.ID','Country.of.Birth.1','Sponsor.Code','Grant.Category.Code','Start.date'
#            ,'No..of.Years.in.Uni.at.Time.of.Grant.1'], axis=1, inplace = False)
x = pd.get_dummies(x, drop_first = True)

In [28]:
#df__ = pd.concat([y,x], axis = 1)
#df__= df__.rename(columns={'0': 'Grant'})
#abs( df__.corr()['Grant.Status'].sort_values(ascending=False  ) )


In [29]:
def algo_test(x,y):
#def algo_test(x_train,x_test,y_train,y_test):
    
    import numpy as np

    from scipy import stats
    import matplotlib.pyplot as plt
    %matplotlib inline 
    import seaborn as sns


    from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
    from sklearn.linear_model import LinearRegression, ElasticNet, Ridge, Lasso
    from sklearn.tree import ExtraTreeClassifier
    from sklearn.ensemble import GradientBoostingRegressor
    from xgboost import XGBRegressor 

    from sklearn.model_selection import train_test_split

    from sklearn.model_selection import train_test_split
    from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
    from sklearn.naive_bayes import GaussianNB
    from sklearn.naive_bayes import BernoulliNB
    from sklearn.neighbors import KNeighborsClassifier
    from sklearn.linear_model import LogisticRegression
    from sklearn.tree import DecisionTreeClassifier
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.ensemble import ExtraTreesClassifier
    from xgboost import XGBClassifier

    import warnings
    warnings.filterwarnings('ignore')
#plt.style.use('')

    
    
    G = GaussianNB()
    B = BernoulliNB()
    K = KNeighborsClassifier()
    L = LogisticRegression()
    D = DecisionTreeClassifier()
    RF = RandomForestClassifier()
    ETC = ExtraTreesClassifier()
    XG = XGBClassifier()

    
    x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2,random_state = 13)
    
    algos = [G,B,L,D, RF, ETC, XG]
    #algos = [G,B,L,D,  RF, ETC]
    
    #algo_names = [ "Gaussian", "Bernoulli", "K-Neighbors", "Logistic Regression", "Decision Tree", "Random Forest", "ExtraTreeClassifier" ]
    algo_names = [ "Gaussian", "Bernoulli","Logistic Regression", "Decision Tree", \
                  "Random Forest", "ExtraTreeClassifier","XGBClassifier" ]
    
    ASC = [];
    
    result =  result = pd.DataFrame(columns =['Accuracy_Score'], index = algo_names)
    
    i = 0;
    for algo in algos :
        
        algo.fit(x_train,y_train)
        #print (accuracy_score(  y_test, algo.predict(x_test) ))
        ASC.append(  accuracy_score(  y_test, algo.predict(x_test) ) )
        
        print( "Confusion matrix: ",format(algo_names[i]) )
        i = i+1;
        print ( confusion_matrix(algo.predict(x_test),y_test) )
        #print (classification_report(y_test,algo.predict(x_test) ))
        
        #algo.fit(x,y)
        #print (accuracy_score(  y, algo.predict(x) ))
        #ASC.append(  accuracy_score(  y, algo.predict(x) ) )
    
    
    result.Accuracy_Score = ASC;

    return result.sort_values('Accuracy_Score', ascending=False)

In [30]:
algo_test(x,y)

Confusion matrix:  Gaussian
[[371 240]
 [317 298]]
Confusion matrix:  Bernoulli
[[576 172]
 [112 366]]
Confusion matrix:  Logistic Regression
[[608 472]
 [ 80  66]]
Confusion matrix:  Decision Tree
[[517 150]
 [171 388]]
Confusion matrix:  Random Forest
[[591 145]
 [ 97 393]]
Confusion matrix:  ExtraTreeClassifier
[[579 166]
 [109 372]]
Confusion matrix:  XGBClassifier
[[559 135]
 [129 403]]


Accuracy_Score
Random Forest              0.802610
XGBClassifier              0.784666
ExtraTreeClassifier        0.775693
Bernoulli                  0.768352
Decision Tree              0.738173
Logistic Regression        0.549755
Gaussian                   0.545677